sudo: false
before_install:
  - openssl req -new -newkey rsa:4096 -days 365 -nodes -x509 -subj "/C=US/ST=Denial/L=Springfield/O=Dis/CN=localhost"   -keyout /tmp/localhost.key -out /tmp/localhost.crt
  - curl -s https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/tar/elasticsearch/2.0.0/elasticsearch-2.0.0.tar.gz  > elasticsearch.tar.gz
  - mkdir elasticsearch && tar -xzf elasticsearch.tar.gz --strip-components=1 -C ./elasticsearch/.
  - ln -sn ../../spec/fixtures/scripts elasticsearch/config/.
  - cd elasticsearch && bin/elasticsearch -Des.script.inline=on -Des.script.indexed=on &
  - sleep 10 && curl http://localhost:9200
language: ruby
cache: bundler
rvm:
  - jruby-1.7.23
script: bundle exec rspec spec && bundle exec rspec spec --tag integration
